[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
registro_asistencia = "D8Tzg8afoUnq2WiXW2qDEGSC2ENH8QYH122yMeyrbazY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
